theme: jekyll-theme-minimal
title: Sinduja S
description: >
  <h3>Data Scientist</h3>
  <p>
    <a href="https://www.linkedin.com/in/sindujasivasailam" target="_blank">LinkedIn: Sinduja S</a> 
    <br>
    <br>
    <b>Skills:</b>
    <ul>
      <li>SQL</li>
      <li>Python</li>
      <li>Data Analysis</li>
      <li>Machine Learning</li>
      <li>Data Visualization</li>
    </ul>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
  </p>
---
