---
layout: default
title: Sai
description: "Data Scientist with skills in SQL, Python, Data Analysis, Machine Learning, and Data Visualization."
theme: lanyon
---

## Data Scientist

**Skills:**

- SQL
- Python
- Data Analysis
- Machine Learning
- Data Visualization
