theme: jekyll-theme-minimal

# Site settings
title: Sainath
description: Data Scientist
baseurl: "/repository-name" # If your site is hosted in a subdirectory

# URL settings
url: "https://www.linkedin.com/in/SindujaSivasailam" # Replace with your GitHub Pages URL

# Navigation
navbar:
  title: Data Science Project
  items:
    - text: Home
      url: /
    - text: About
      url: /about

# Footer
footer:
  text: "Copyright © 2023 Your Name"

# Other configurations
markdown: kramdown
