title: Sinduja S
# logo: /assets/dv.jpg
description: Data Scientist
description: Skills: SQL | Python | MATLAB
[https://www.linkedin.com/in/abc](https://www.linkedin.com/in/yourusername)
#show_downloads: true
theme: jekyll-theme-minimal

# theme: jekyll-theme-cayman

# theme: jekyll-theme-dinky
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-architect


