title: Sinduja S
# logo: /assets/dv.jpg
description: Data Scientist
linkedin: https://www.linkedin.com/in/your-linkedin-username
#show_downloads: true
theme: jekyll-theme-minimal

# theme: jekyll-theme-cayman

# theme: jekyll-theme-dinky
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-architect


