theme: jekyll-theme-minimal
title: Sinduja S
description: >
  <h2>Data Scientist</h2>
  <p>
    <b>LinkedIn:</b> <a href="https://www.linkedin.com/in/sindujasivasailam" target="_blank"> Sinduja S</a> 
    <br>
    <br>
    <b>Skills:</b>
    <ul>
      <li>Data Analysis</li>
      <li>Machine Learning</li>
      <li>Data Visualization</li>
      <li>Deep Learning</li>
      <li>SQL</li>
      <li>Python</li>
    </ul>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
  </p>
---
